services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
  temporal:
    container_name: temporal
    depends_on:
      - db
    environment:
      - DB=postgres
      - DB_PORT=5432
      - POSTGRES_USER=myuser
      - POSTGRES_PWD=mypassword
      - POSTGRES_SEEDS=db
      - DYNAMIC_CONFIG_FILE_PATH=config/dynamicconfig/config.yaml
    image: temporalio/auto-setup:1.23
    ports:
      - 7233:7233
    volumes:
      - ./config:/etc/temporal/config/dynamicconfig
      - ./certs/certs:/etc/temporal/config/certs
    labels:
      kompose.volume.type: configMap
  temporal-ui:
    container_name: temporal-ui
    depends_on:
      - temporal
    environment:
      - TEMPORAL_ADDRESS=temporal:7233
      - TEMPORAL_CORS_ORIGINS=http://localhost:3000
    image: temporalio/ui:latest
    ports:
      - 8080:8080
  temporal-admin-tools:
    image: temporalio/admin-tools:${SERVER_TAG:-latest}
    stdin_open: true
    tty: true
    environment:
      - "TEMPORAL_CLI_ADDRESS=temporal:7236"
    depends_on:
      - temporal

volumes:
  db-data: