log:
  stdout: true
  level: info
  
global:
  tls:
    internode:
      server:
        certFile: /etc/temporal/config/certs/cluster/cluster.cert
        keyFile: /etc/temporal/config/certs/cluster/cluster.key
        requireClientAuth: true
        clientCaFiles:
          - /etc/temporal/config/certs/cluster.cert
      client:
        serverName: dnsSanInInternodeCertificate
        rootCaFiles:
          - /etc/temporal/config/certs/cluster.cert
    frontend:
      server:
        certFile: /etc/temporal/config/certs/client.cert
        keyFile: /etc/temporal/config/certs/client.key
        requireClientAuth: true
        clientCaFiles:
          - /etc/temporal/config/certs/cluster.cert
          - /etc/temporal/config/certs/ca.cert
          - /etc/temporal/config/certs/ca.cert
      client:
        serverName: dnsSanInFrontendCertificate
        rootCaFiles:
          - /etc/temporal/config/certs/ca.cert